openapi: "3.0.0"
info:
  title: Learn express and swagger
  description: LCO - a course segment about writing docs
  version: 1.1.0
  contact:
    email: kacper.figa@protonmail.com
    url: "https://kacperfiga-frontend.netlify.app/"

  # servers:
  #   - url: "https://localhost:2137/api/v1"
  #     description: server for localhost - secure
  #   - url: "http://localhost:2137/api/v1"
  #     description: server for localhost - regular

servers:
  - url: "{protocol}://localhost:2137/api/{version}"
    description: for localhost
    variables:
      version:
        enum:
          - v1
          - v2
      protocol:
        enum:
          - http
          - https
